In [1]:
#Question 1 Answer= A Python library is a collection of pre-written code that you can use in your own programs to perform common tasks and functions.
These libraries can include modules (individual files containing Python code) and packages (directories containing multiple modules and possibly other packages). 
Libraries help in extending Python’s capabilities and making development more efficient.
  Cell In[1], line 3
    Libraries help in extending Python’s capabilities and making development more efficient.
                                      ^
SyntaxError: invalid character '’' (U+2019)
#question 2 Answer = The primary differences between NumPy arrays and Python lists involve functionality, performance, and usage. Here’s a detailed comparison:

1. Data Structure
NumPy Array:
A NumPy array (ndarray) is a grid of values, all of the same type, indexed by a tuple of non-negative integers.
It supports multi-dimensional data (2D, 3D, etc.).
More suitable for mathematical and numerical operations.
Python List:
A Python list is an ordered collection of items which can be of different types.
Typically used for general-purpose programming.
2. Homogeneity
NumPy Array:
Elements must be of the same data type (e.g., all integers, all floats).
Python List:
Elements can be of different data types (e.g., integers, strings, floats).
#question 3
import numpy as np
arr1 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                [9, 10, 11, 12]])
arr1
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])
arr1.size
12
arr1.shape
(3, 4)
arr1.ndim
2
#question 4
arr1
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])
arr1[0]
array([1, 2, 3, 4])
#question 5
arr1[2,3]
12
#question 6
arr1
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])
arr1[1::2, 1::2]
array([[6, 8]])
#question 7
arr2 = np.random.rand(3, 3)
arr2
array([[0.3374499 , 0.53049217, 0.59022539],
       [0.05981097, 0.93883141, 0.24417458],
       [0.41182419, 0.43780112, 0.49440153]])
#question 8
np.random.rand generates random numbers uniformly distributed between 0 and 1, 
while np.random.randn generates random numbers from a standard normal distribution with a mean of 0 and a standard deviation of 1.
#question 10
arr1
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])
arr1.T
array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])
#question 11
a = arr1
b = arr1
a
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])
b
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])
a * b
array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])
a @ b
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[42], line 1
----> 1 a @ b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)
a + b
array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])
b-a
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])
b/a
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])
#question 12
ou can use the np.ndarray.byteswap() function in NumPy to swap the byte order of an array. 
#question 13
The np.linalg.inv function in NumPy computes the inverse of a square matrix, which is significant in solving systems of linear equations and in various mathematical computations where division by matrices is required.
  Cell In[48], line 1
    The np.linalg.inv function in NumPy computes the inverse of a square matrix, which is significant in solving systems of linear equations and in various mathematical computations where division by matrices is required.
        ^
SyntaxError: invalid syntax
#question 14
The np.reshape function in NumPy changes the shape of an array without changing its data. It allows you to specify the new shape of the array using a tuple of integers representing the desired dimensions.
Example: new_array = np.reshape(old_array, (2, 3)) reshapes old_array into a 2x3 array.
#question 15
Broadcasting in NumPy is a mechanism that allows arrays of different shapes to be used together in arithmetic operations. It enables NumPy to perform element-wise operations on arrays even if their shapes are not identical, by implicitly replicating elements as needed to make the shapes compatible. This helps in writing concise and efficient code for array computations without explicitly copying data.
  Cell In[50], line 1
    Broadcasting in NumPy is a mechanism that allows arrays of different shapes to be used together in arithmetic operations. It enables NumPy to perform element-wise operations on arrays even if their shapes are not identical, by implicitly replicating elements as needed to make the shapes compatible. This helps in writing concise and efficient code for array computations without explicitly copying data.
                               ^


SyntaxError: invalid character '’' (U+2019) (2008502290.py, line 3)